### ISSUE TITLE
The MathNet.Numerics.dll is too big！1.51 MB

### ISSUE THREAD

**Issue by ysdy44** [nenoNaninu/HomographySharp#40]
I tried to use this library, but it is too big.
In the "bin\x64\Debug" folder, there is a huge file called MathNet.Numerics.dll.
Do you have any lighter than this?

**Comment by nenoNaninu** [comment]
There may be, but I have no motivation to use them instead of Math.NET Numerics.
Math.NET Numerics is the de facto standard library for numerical calculation in C# and is well proven and tested.

If you are concerned about the size of the library, I recommend that you consider enabling [trimming](https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained).

**Comment by ysdy44** [comment]
Thanks for your answer, but how to "enabling trimming" on [UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide) application?

**Comment by nenoNaninu** [comment]
Look it up yourself.

**Comment by ysdy44** [comment]
Trimming is only supported in .NET 6, .NET 5, .NET Core, not [windows runtime](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/).

**Comment by nenoNaninu** [comment]
Trimming is one of many options. Find out for yourself which option is best for you.
